FROM bitnami/spark:3.2.0

USER root

RUN curl https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.11.375/aws-java-sdk-bundle-1.11.375.jar --output /opt/bitnami/spark/jars/aws-java-sdk-bundle-1.11.375.jar
RUN curl https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.2.0/hadoop-aws-3.2.0.jar --output /opt/bitnami/spark/jars/hadoop-aws-3.2.0.jar
# RUN curl https://repo1.maven.org/maven2/net/java/dev/jets3t/jets3t/0.9.4/jets3t-0.9.4.jar --output /opt/bitnami/spark/jars/jets3t-0.9.4.jar
RUN curl https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk/1.11.375/aws-java-sdk-1.11.375.jar  --output /opt/bitnami/spark/jars/aws-java-sdk-1.11.375.jar
COPY ./dags /opt/bitnami/spark

COPY ./requirements_copy.txt /
RUN pip install -r /requirements_copy.txt